### ISSUE TITLE
Add apple wallet support

### ISSUE THREAD

**Issue by pixix4** [ascii-dresden/ascii-pay-server#13]
Create apple wallet card. Required features:
- Template `StoreCard`
- Location triggering
- Auto update for balance

A reference implementation can be found at: [Wallet Developer Guide](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195)

Maybe needs a MacBook for certificate creation?

**Comment by Feliix42** [comment]
Maybe some input from @kiliankoe wouldn't hurt as well 😅

**Comment by kiliankoe** [comment]
> Maybe needs a MacBook for certificate creation?

Not afaik. But it does require a cert which is periodically (once a year) updated (manually, lol). 

Very cool project btw!
