### ISSUE TITLE
Secure transaction routes with client ssl certificate

### ISSUE THREAD

**Issue by pixix4** [ascii-dresden/ascii-pay-server#16]
`/api/v1/transaction/*`

**Comment by pixix4** [comment]
All `/api/v1` routes can only be accessed with valid login session (`MEMBER` or `ADMIN`) or with http-header attribute `X-Client-Cert: true`. The reverse proxy is responsible to set the correct header attribute if a valid ssl client certificate is present

**Comment by bennofs** [comment]
Perhaps it would be better to use some configurable secret as the expected value for the header. This would prevent a pitfall that might happen during deployment: If we're not careful to remove any such header from incoming requests, an attack might set this header on his own request and bypass authentication. This can of course be prevented in the reverse proxy, but with a secret, it would be more reliable against accidental misconfiguration.

Not sure if it would be a good idea to re-use `Authorization: bearer <token here>` as header for this?
