### ISSUE TITLE
Add mail support

### ISSUE THREAD

**Issue by pixix4** [ascii-dresden/ascii-pay-server#17]
- [x] Send invitation links to mail
- [x] Add testmail functionality

## Sending opt-in monthly reports
- [x] Add account setting for opt-int to monthly reports
- [x] Add UI option to enable reports
- [x] implement mail sending
- [x] Assemble report
- [x] Restrict enabling monthly reports to accounts with mail address
- [x] disable monthly reports when removing mail address

## Finishing up
- [x] Run rustfmt on all edited files

**Comment by Feliix42** [comment]
I'd love to give this a try to get properly involved in the project once again. :)

**Comment by Feliix42** [comment]
There is a function to send a test mail, but we should settle for routes for admin-related stuff first so I can assign a route to this.

I would propose the obvious `/admin` route?

**Comment by Feliix42** [comment]
Also, the monthly report is going to be fun, as we have no scheduler that could take care of running monthly jobs.
I see three ways to solve this:

1. Hack some form of job scheduler for repeated jobs into the system or find a suitable crate that is interoperable with actix.
2. Provide a Cronjob Config that has to be installed on the host server to send these reports monthly.
3. Do something similar as seen in Wordpress. They have a file called `wp-cron.php` which is run when a user visits the page and a certain timespan has passed (i.e., more than a month has elapsed in our case). Might be a little hacky but may be implementable as some sort of Middleware, using the [`Condition`](https://docs.rs/actix-web/2.0.0/actix_web/middleware/struct.Condition.html) middleware.

**Comment by pixix4** [comment]
I would suggest a mix of 2. and 3.:

Create a route (eg. `/admin/cron`) that is called every day with via a cron job. So not every call has to check for scheduled jobs. This could additionally be used to validate transaction (daily?)

**Comment by Feliix42** [comment]
The PR for this issue only implements basic report functionality. The follow-up issue for this is #26.
